import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: "var(--font-sans)",
      },
      colors: {
        primary: {
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
        },
        neutral: {
          25: "var(--color-neutral-25)",
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
          950: "var(--color-neutral-950)",
        },
        red: "var(--color-red)",
        green: "var(--color-green)",
        yellow: "var(--color-yellow)",
        white: "var(--color-white)",
        black: "var(--color-black)",
      },
      spacing: {
        xxs: "var(--spacing-xxs)",
        xs: "var(--spacing-xs)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
        "4xl": "var(--spacing-4xl)",
        "5xl": "var(--spacing-5xl)",
        "6xl": "var(--spacing-6xl)",
        "7xl": "var(--spacing-7xl)",
        "8xl": "var(--spacing-8xl)",
        "9xl": "var(--spacing-9xl)",
        "10xl": "var(--spacing-10xl)",
        "11xl": "var(--spacing-11xl)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        xxs: "var(--radius-xxs)",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        "4xl": "var(--radius-4xl)",
        full: "var(--radius-full)",
      },
      fontSize: {
        "display-3xl": ["3.75rem", { lineHeight: "4.5rem" }],
        "display-2xl": ["3rem", { lineHeight: "3.75rem", letterSpacing: "-0.02em" }],
        "display-xl": ["2.5rem", { lineHeight: "3rem", letterSpacing: "-0.02em" }],
        "display-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.02em" }],
        "display-md": ["2rem", { lineHeight: "2.5rem" }],
        "display-sm": ["1.75rem", { lineHeight: "2.375rem" }],
        "display-xs": ["1.5rem", { lineHeight: "2.25rem" }],
        "text-xl": ["1.25rem", { lineHeight: "2.125rem" }],
        "text-lg": ["1.125rem", { lineHeight: "2rem" }],
        "text-md": ["1rem", { lineHeight: "1.875rem" }],
        "text-sm": ["0.875rem", { lineHeight: "1.75rem" }],
        "text-xs": ["0.75rem", { lineHeight: "1.5rem" }],
      },
    },
  },
  plugins: [],
};
export default config;
